#!/usr/bin/env bash
# clean.sh — remove everything generated by multiscraper.
#
# Removes:
#   - cache.db (SQLite cache) and its WAL/SHM sidecars
#   - reports/ (per-system CSV files)
#   - media/ (downloaded covers, screenshots, videos)
#   - scrape.csv (legacy single-run CSV if present)
#   - run.log.jsonl (if present)
#
# Does NOT touch:
#   - .env (real credentials)
#   - config/*.yaml (your real config)
#   - .venv/, __pycache__/, .mypy_cache/, etc. (build artifacts)
#
# Usage:
#   ./scripts/clean.sh          # asks for confirmation
#   ./scripts/clean.sh --force   # no confirmation
#   ./scripts/clean.sh --dry-run # show what would be removed

set -euo pipefail

FORCE=0
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --force|-f) FORCE=1 ;;
        --dry-run|-n) DRY_RUN=1 ;;
        -h|--help)
            echo "Usage: $0 [--force] [--dry-run]"
            echo "  --force     don't ask for confirmation"
            echo "  --dry-run   show what would be removed without removing"
            exit 0
            ;;
        *)
            echo "Unknown argument: $arg" >&2
            exit 1
            ;;
    esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Targets: relative to repo root. Each entry is "<description>|<path>".
TARGETS=(
    "SQLite cache (cache.db + WAL/SHM)|cache.db"
    "Legacy single-run CSV|scrape.csv"
    "SQLite cache (cache.db-journal)|cache.db-journal"
    "Reports directory (per-system CSVs)|reports"
    "Media root (downloaded covers, videos)|media"
    "Run log (JSONL)|run.log.jsonl"
)

ITEMS=()
for entry in "${TARGETS[@]}"; do
    path="${entry#*|}"
    if [[ -e "$path" ]]; then
        ITEMS+=("$entry")
    fi
done

if [[ ${#ITEMS[@]} -eq 0 ]]; then
    echo "Nothing to clean — multiscraper has not generated any artifacts yet."
    exit 0
fi

echo "The following will be removed:"
echo
for entry in "${ITEMS[@]}"; do
    desc="${entry%|*}"
    path="${entry#*|}"
    if [[ -d "$path" ]]; then
        size=$(du -sh "$path" 2>/dev/null | cut -f1)
        printf "  %-40s  %s  (%s)\n" "$desc" "$path" "$size"
    else
        size=$(du -h "$path" 2>/dev/null | cut -f1)
        printf "  %-40s  %s  (%s)\n" "$desc" "$path" "$size"
    fi
done
echo

if [[ $DRY_RUN -eq 1 ]]; then
    echo "(dry run: nothing was removed)"
    exit 0
fi

if [[ $FORCE -ne 1 ]]; then
    read -r -p "Remove these? [y/N] " ans
    case "$ans" in
        y|Y|yes|YES) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

for entry in "${ITEMS[@]}"; do
    path="${entry#*|}"
    if [[ -d "$path" ]]; then
        rm -rf "$path"
    else
        rm -f "$path"
    fi
    echo "  removed: $path"
done

echo
echo "Done."
